-- ============================================================
-- Migration: 20260612000002_staff_documents_bucket_private.sql
-- Purpose:   Make the staff-documents storage bucket private so
--            that objects are no longer accessible via public
--            URLs and can only be reached via signed URLs
--            generated by the application.
--
-- !! APPLY ONLY AFTER the signed-URL code change is deployed
--    to production.  Applying this before the code change will
--    break all existing document links in the UI. !!
--
-- Pre-condition: src/App.jsx handleUpload stores the storage
--   path (not a public URL) in staff_documents.file_url, and
--   loadDocs generates a signed URL via createSignedUrl(3600)
--   for display.  hrService.js upload() likewise stores the
--   path, and getByStaff() returns rows with a displayUrl
--   field generated via createSignedUrl(3600).
-- ============================================================

UPDATE storage.buckets
SET    public = false
WHERE  id = 'staff-documents';
